name: Bug report
description: Report an issue to help improve the nose_elf.
labels: ['bug']
body:
- type: dropdown
  id: interaction
  attributes:
    label: Which part of the bot is affected by the bug?
    options:
      - Commands
      - Buttons
      - Select Menu
      - General Audio playback
      - Other (please specify in description)
  validations:
    required: true
 
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the question or issue, also include what you tried and what didn't work
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this bug?
    validations:
      required: false
  - type: input
    id: command
    attributes:
      label:  Affected command
      description:  "If the bug is related to a command, please enter the command here"
      placeholder:  N/A
      value:  "/"
    valildations:
      required: false
